apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: apacheproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache-container
          image: httpd:latest
          ports:
            - containerPort: 90
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"  # Requerimiento mínimo de CPU
            limits:
              memory: "200Mi"
              cpu: "100m"  # Límite máximo de CPU
